export const POINT_SEQUENCE_LIST = 'POINT_SEQUENCE_LIST';
export const PERSONAL_SETTING = 'PERSONAL_SETTING';
export const FUNC_GO_BACK = 'GO_BACK';
export const FUNC_CLOSE = 'CLOSE';
export const FUNC_SETTING = 'SETTING';
